#!/usr/bin/env bash

#docker run -d --name gitlab-runner-config \
#    -v /etc/gitlab-runner \
#    busybox:latest \
#    /bin/true

docker run -d --name gitlab-runner \
    -v /var/run/docker.sock:/var/run/docker.sock \
    --volumes-from gitlab-runner-config \
    gitlab/gitlab-runner:latest
